CREATE DATABASE IF NOT EXISTS productservice;
CREATE DATABASE IF NOT EXISTS userservice;
CREATE DATABASE IF NOT EXISTS paymentservice;
CREATE DATABASE IF NOT EXISTS cartservice;
CREATE DATABASE IF NOT EXISTS orderservice;
